# Generated by Django 5.0.1 on 2024-02-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('vendedor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
