# Generated by Django 5.0.1 on 2024-02-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
