# Generated by Django 5.0.1 on 2024-02-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0003_venta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(default='Ingresado', max_length=50),
        ),
    ]
