# Generated by Django 5.0.1 on 2024-02-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0005_alter_trabajo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado'), ('Sin solución', 'Sin solución'), ('Entregado', 'Entregado')], default='Ingresado', max_length=50),
        ),
    ]
