# Generated by Django 5.0.1 on 2024-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0006_alter_trabajo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('condicion', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=50)),
                ('precio', models.IntegerField()),
                ('vendedor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
