# Generated by Django 5.0.1 on 2024-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0007_publicacion_delete_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='condicion',
            field=models.CharField(max_length=50),
        ),
    ]
