# Generated by Django 5.0.1 on 2024-02-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0008_alter_publicacion_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='condicion',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=50),
        ),
    ]
