# Generated by Django 5.0.1 on 2024-02-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0009_alter_publicacion_condicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
    ]
